FROM python:3.14-alpine
COPY --from=ghcr.io/astral-sh/uv:0.11.16-python3.14-alpine /usr/local/bin/uv /usr/local/bin/uv
WORKDIR /app
RUN apk --no-cache upgrade && apk --no-cache add make
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_PYTHON_DOWNLOADS=0

COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

COPY --chown=1000:1000 . .
RUN chmod 777 .
CMD ["make", "full-test"]
