{
 "title": "Transmission",
 "description": "Dashboard for Transmission InfluxDB Exporter",
 "tags": [
  "transmission",
  "torrent"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "intervalOffset",
    "label": "Double seconds_between_collections variable from transmission exporter",
    "query": "120"
   }
  ]
 },
 "panels": [
  { "title": "Individual Torrents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Torrents With Errors",
   "type": "table",
   "description": "Torrents that had errors during the interval [10 minutes by default]",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"torrents\" and r.error != \"0\" and r._field == \"downloaded\")\n  |> group(columns: [\"infohash\", \"client_name\"])\n  |> last()\n  |> keep(columns: [\"client_name\", \"torrent_name\", \"tracker\", \"error\", \"_time\"])\n  |> group(columns: [])\n  |> rename(columns: {_time: \"Last Error Time\", client_name: \"Client Name\", torrent_name: \"Torrent Name\", tracker: \"Tracker\", error: \"Error Code\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Uploaded Torrents (Past Day)",
   "type": "table",
   "description": "The top 10 torrents by upload over the past 24 hours (aggregated from all clients)\n\nNote: This is hard-coded past 1 day only! No dynamic ranges supported as to not accidentally kill DB for a call that is too demanding",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "preFilter = from(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"torrents\" and r._field == \"uploaded\")\n  |> group(columns: [\"infohash\", \"client_name\"])\n  |> sort(columns: [\"_time\"])\n\nfirstVals = preFilter\n  |> first()\n  |> group(columns: [\"infohash\", \"torrent_name\", \"tracker\"])\n  |> sum(column: \"_value\")\n\nlastVals = preFilter\n  |> last()\n  |> group(columns: [\"infohash\", \"torrent_name\", \"tracker\"])\n  |> sum(column: \"_value\")\n  \njoin(tables: {first: firstVals, last: lastVals}, on: [\"infohash\", \"torrent_name\", \"tracker\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_last - r._value_first }))\n  |> keep(columns: [\"_value\", \"torrent_name\", \"tracker\"])\n  |> group(columns: [])\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 10)\n  |> rename(columns: {_value: \"Uploaded\", torrent_name: \"Torrent Name\", tracker: \"Tracker\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Summary (Aggregate Clients)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Free Space",
   "type": "stat",
   "description": "Free space remaining in download folder (all clients free space added together)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"free_space\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Time Total Downloaded",
   "type": "stat",
   "description": "Total amount of data downloaded over all time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"downloaded\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Time Total Uploaded",
   "type": "stat",
   "description": "Total amount of data uploaded over all time",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"uploaded\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downloaded Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"downloaded\")\n  |> window(every: 1d)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])\n  |> difference(columns: [\"_value\"], nonNegative: true)\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uploaded Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"uploaded\")\n  |> window(every: 1d)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])\n  |> difference(columns: [\"_value\"], nonNegative: true)\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Summary (Per Client)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Free Space",
   "type": "stat",
   "description": "Free space remaining in download folder",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"free_space\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Time Total Downloaded",
   "type": "stat",
   "description": "Total amount of data downloaded over all time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"downloaded\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Time Total Uploaded",
   "type": "stat",
   "description": "Total amount of data uploaded over all time",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"uploaded\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downloaded Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"downloaded\")\n  |> window(every: 1d)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])\n  |> difference(columns: [\"_value\"], nonNegative: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uploaded Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"uploaded\")\n  |> window(every: 1d)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])\n  |> difference(columns: [\"_value\"], nonNegative: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Current (Aggregate Clients)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Upload Speed",
   "type": "graph",
   "description": "Current upload speed of all torrent client(s) combined",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"upload_speed\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: r._value * 8}))\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "graph",
   "description": "Current download speed of all torrent client(s) combined",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"download_speed\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: r._value * 8}))\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "description": "Current connected peers count of all torrent client(s) combined",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"connected_peers\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errored Torrents",
   "type": "graph",
   "description": "Current errored torrent counts of all torrent client(s) combined",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"errored\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stopped Torrents",
   "type": "graph",
   "description": "Current stopped torrent counts of all torrent client(s) combined",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"stopped\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seeding Torrents",
   "type": "graph",
   "description": "Current seeding torrent counts of all torrent client(s) combined",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"seeding\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downloading Torrents",
   "type": "graph",
   "description": "Current downloading torrent counts of all torrent client(s) combined",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"downloading\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Current (Per Client)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Upload Speed",
   "type": "graph",
   "description": "Current upload speed of torrent client(s)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"upload_speed\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value * 8}))\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "graph",
   "description": "Current download speed of torrent client(s)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"download_speed\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value * 8}))\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "description": "Current connected peers count of torrent client(s)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"connected_peers\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errored Torrents",
   "type": "graph",
   "description": "Current errored torrent counts of torrent client(s)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"errored\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stopped Torrents",
   "type": "graph",
   "description": "Current stopped torrent counts of torrent client(s)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"stopped\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seeding Torrents",
   "type": "graph",
   "description": "Current seeding torrent counts of torrent client(s)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"seeding\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downloading Torrents",
   "type": "graph",
   "description": "Current downloading torrent counts of torrent client(s)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"stats\" and r._field == \"downloading\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"client_name\"])\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Trackers (Aggregate Clients)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Upload Speed (By Tracker)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"trackers\" and r._field == \"upload_speed\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\", \"tracker\"])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: r._value * 8}))\n  |> group(columns: [\"tracker\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Speed (By Tracker)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"trackers\" and r._field == \"download_speed\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\", \"tracker\"])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: r._value * 8}))\n  |> group(columns: [\"tracker\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uploaded Per Day (By Tracker)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"trackers\" and r._field == \"uploaded\")\n  |> window(every: 1d)\n  |> last()\n  |> group(columns: [\"_time\", \"tracker\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"tracker\"])\n  |> difference(columns: [\"_value\"], nonNegative: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downloaded Per Day (By Tracker)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"trackers\" and r._field == \"downloaded\")\n  |> window(every: 1d)\n  |> last()\n  |> group(columns: [\"_time\", \"tracker\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"tracker\"])\n  |> difference(columns: [\"_value\"], nonNegative: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seeding Torrents (By Tracker)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"trackers\" and r._field == \"seeding\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\", \"tracker\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"tracker\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errored Torrents (By Tracker)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\nfrom(bucket: \"transmission/transmission_exporter_retention\")\n  |> range(start: experimental.subDuration(d: ${intervalOffset}s, from: v.timeRangeStart), stop: experimental.addDuration(d: ${intervalOffset}s, to: v.timeRangeStop))\n  |> filter(fn: (r) => r._measurement == \"trackers\" and r._field == \"errored\")\n  |> window(every: v.windowPeriod)\n  |> last()\n  |> group(columns: [\"_time\", \"tracker\"])\n  |> sum(column: \"_value\")\n  |> group(columns: [\"tracker\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}